#ifndef __BMPDATAARRAY_H
#define __BMPDATAARRAY_H

extern unsigned char pic_barcode_ppg_D_png[]; // 0
extern unsigned char pic_barcode_ppg_3_png[]; // 1
extern unsigned char pic_barcode_ppg_1_png[]; // 2
extern unsigned char pic_barcode_ppg_F_png[]; // 3
extern unsigned char pic_barcode_ppg_blank_png[]; // 4
extern unsigned char pic_barcode_ppg_5_png[]; // 5
extern unsigned char pic_barcode_ppg_E_png[]; // 6
extern unsigned char pic_barcode_ppg_9_png[]; // 7
extern unsigned char pic_barcode_ppg_C_png[]; // 8
extern unsigned char pic_barcode_ppg_4_png[]; // 9
extern unsigned char pic_barcode_ppg_8_png[]; // 10
extern unsigned char pic_barcode_ppg_A_png[]; // 11
extern unsigned char pic_barcode_ppg_B_png[]; // 12
extern unsigned char pic_barcode_ppg_6_png[]; // 13
extern unsigned char pic_barcode_ppg_2_png[]; // 14
extern unsigned char pic_barcode_ppg_7_png[]; // 15
extern unsigned char pic_barcode_ppg_0_png[]; // 16
extern unsigned char pic_kb_ic_key_cap_lock_off_png[]; // 17
extern unsigned char pic_kb_ic_key_cap_lock_pressed_png[]; // 18
extern unsigned char pic_kb_ic_key_cap_lock_on_png[]; // 19
extern unsigned char pic_kb_ic_key_del_pressed_png[]; // 20
extern unsigned char pic_kb_ic_key_png[]; // 21
extern unsigned char pic_kb_ic_key_del_png[]; // 22
extern unsigned char pic_kb_ic_key_space_bar_pressed_png[]; // 23
extern unsigned char pic_kb_ic_key_pressed_png[]; // 24
extern unsigned char pic_kb_ic_key_space_bar_png[]; // 25
extern unsigned char pic_heater_set_time_3_png[]; // 26
extern unsigned char pic_heater_lefticonpress[]; // 27
extern unsigned char pic_heater_work_time_9_png[]; // 28
extern unsigned char pic_heater_work_time_6_png[]; // 29
extern unsigned char pic_heater_set_time_9_png[]; // 30
extern unsigned char pic_heater_set_time_2_png[]; // 31
extern unsigned char pic_heater_work_time_7_png[]; // 32
extern unsigned char pic_heater_set_time_5_png[]; // 33
extern unsigned char pic_heater_bg_newzhengzhu[]; // 34
extern unsigned char pic_heater_set_time_1_png[]; // 35
extern unsigned char pic_heater_work_time_2_png[]; // 36
extern unsigned char pic_heater_circle_progress_png[]; // 37
extern unsigned char pic_heater_set_time_0_png[]; // 38
extern unsigned char pic_heater_bg_progress[]; // 39
extern unsigned char pic_heater_Heat_Bg[]; // 40
extern unsigned char pic_heater_set_time_6_png[]; // 41
extern unsigned char pic_heater_color_progress[]; // 42
extern unsigned char pic_heater_set_time_7_png[]; // 43
extern unsigned char pic_heater_work_time_4_png[]; // 44
extern unsigned char pic_heater_work_time_8_png[]; // 45
extern unsigned char pic_heater_lefticon[]; // 46
extern unsigned char pic_heater_set_time_4_png[]; // 47
extern unsigned char pic_heater_work_time_1_png[]; // 48
extern unsigned char pic_heater_set_time_8_png[]; // 49
extern unsigned char pic_heater_work_time_5_png[]; // 50
extern unsigned char pic_heater_work_time_3_png[]; // 51
extern unsigned char pic_heater_work_time_0_png[]; // 52
extern unsigned char pic_fail_error_EF[]; // 53
extern unsigned char pic_fail_error_E8[]; // 54
extern unsigned char pic_fail_error_E3[]; // 55
extern unsigned char pic_fail_error_EA[]; // 56
extern unsigned char pic_fail_error_E7[]; // 57
extern unsigned char pic_fail_error_E6[]; // 58
extern unsigned char pic_fail_error_E1[]; // 59
extern unsigned char pic_fail_error_E4[]; // 60
extern unsigned char pic_fail_error_E2[]; // 61
extern unsigned char pic_fail_error_EB[]; // 62
extern unsigned char pic_fail_error_E5[]; // 63
extern unsigned char pic_tips_btn_home_big_png[]; // 64
extern unsigned char pic_tips_btn_left_big_png[]; // 65
extern unsigned char pic_tips_tips_2[]; // 66
extern unsigned char pic_tips_btn_right_big_png[]; // 67
extern unsigned char pic_tips_back_png[]; // 68
#endif
